import Foundation

// Conservative metadata checks, not an acoustic fingerprint or a guarantee
// that a provider/uploader's metadata is truthful.
enum PWRecordingPolicy {
    static func artistMatches(_ actual: String, _ expected: String) -> Bool {
        let normalized = actual.replacingOccurrences(of: #"(?i)\s*(?:-\s*Topic|VEVO|Official|Officiel)\s*$"#,
                                                     with: "", options: .regularExpression)
        return PWDownloadRules.words(normalized) == PWDownloadRules.words(expected)
    }
    static func recordingRejection(_ candidate: PWAudioCandidate, for track: PWAudioTrack) -> String? {
        if let reason = PWDownloadRules.rejection(candidate, for: track, requireYouTubeID: false) { return reason }
        let found = Set(PWDownloadRules.titleWords(candidate.title)), wanted = Set(PWDownloadRules.titleWords(track.title))
        for word in ["instrumental", "cover", "remix", "live", "karaoke", "sped", "slowed", "nightcore", "acoustic",
                     "pitch", "reverb", "8d", "distorted", "distordue", "modified", "modifie", "remake", "bootleg", "mashup", "speed", "chipmunk"] {
            if found.contains(word) != wanted.contains(word) { return "version" }
        }
        // An extra song title (mashups, medleys) must not match just because it
        // contains the requested title. Permit presentation labels and credits.
        let allowed = wanted.union(PWDownloadRules.words(track.artist)).union([
            "official", "officiel", "officielle", "audio", "video", "music", "clip", "lyrics", "lyric", "visualizer", "visualiser", "hd", "hq", "4k"])
        guard found.isSubset(of: allowed) else { return "title_extra" }
        return nil
    }
    static func youtubeRejection(_ candidate: PWAudioCandidate, for track: PWAudioTrack) -> String? {
        guard PWDownloadRules.identifier(candidate.id, length: 11) else { return "identifier" }
        if let reason = recordingRejection(candidate, for: track) { return reason }
        let artist = candidate.artist.components(separatedBy: " • ").first ?? candidate.artist
        guard artistMatches(artist, track.artist) else { return "artist_identity" }
        guard ["verified_artist", "verified_channel", "topic_pending", "distributed_audio_pending"].contains(candidate.youtubeEvidence) else {
            return "official_unconfirmed"
        }
        return nil
    }
    static func youtubeDescriptionRequired(_ candidate: PWAudioCandidate) -> Bool {
        candidate.youtubeEvidence.hasSuffix("_pending")
    }
    static func distributedDescription(_ description: String) -> Bool {
        let text = description.lowercased()
        return text.contains("provided to youtube by") && text.contains("auto-generated by youtube")
    }
}

enum PWFallbackPolicy {
    static func order(soundCloud: Bool, audius: Bool) -> [String] {
        (soundCloud ? ["soundcloud"] : []) + (audius ? ["audius"] : [])
    }
}
