import Foundation

@main enum SoundCloudRulesTests {
    @MainActor static func main() async throws {
        var count = 0
        func check(_ value: @autoclosure () -> Bool, _ message: String) {
            count += 1; if !value() { fatalError("FAIL: " + message) }
        }
        let track = PWAudioTrack(id: "0123456789ABCDEFGHIJKL", title: "91's", artist: "PNL", duration: 234, isrc: "FRABC1900001")
        var candidate = PWAudioCandidate(id: "aB1_cD2-eF3", title: "PNL - 91’s (Official Audio)", artist: "PNL - Topic", duration: 238)
        check(PWRecordingPolicy.youtubeRejection(candidate, for: track) == "official_unconfirmed", "title alone never proves official origin")
        candidate.youtubeEvidence = "topic_pending"
        check(PWRecordingPolicy.youtubeRejection(candidate, for: track) == nil, "topic artist and apostrophes match")
        check(PWRecordingPolicy.youtubeDescriptionRequired(candidate), "topic names require distribution description")
        check(!PWRecordingPolicy.distributedDescription("Official Audio PNL"), "uploader assertion insufficient")
        check(PWRecordingPolicy.distributedDescription("Provided to YouTube by Label\nAuto-generated by YouTube."), "distribution description")
        var wrong = candidate; wrong.artist = "Fan PNL"; wrong.youtubeEvidence = "verified_artist"
        check(PWRecordingPolicy.youtubeRejection(wrong, for: track) == "artist_identity", "verified fan channel is not artist")
        for version in ["instrumental", "reverb", "8D", "pitch", "sped up", "slowed", "remake", "mashup"] {
            wrong = candidate; wrong.title += " " + version
            check(PWRecordingPolicy.youtubeRejection(wrong, for: track) != nil, "modified version rejected: " + version)
        }
        wrong = candidate; wrong.title += " x Au DD"
        check(PWRecordingPolicy.youtubeRejection(wrong, for: track) == "title_extra", "unlabelled mashup rejected")
        let yt: [String: Any] = ["videoRenderer": ["videoId": candidate.id, "title": ["simpleText": "91's"],
            "ownerText": ["simpleText": "PNL"], "lengthText": ["simpleText": "3:54"],
            "ownerBadges": [["metadataBadgeRenderer": ["style": "BADGE_STYLE_TYPE_VERIFIED_ARTIST"]]]]]
        check(PWDownloadRules.candidates(yt, music: false).first?.youtubeEvidence == "verified_artist", "real artist badge parsed")
        let music: [String: Any] = ["musicResponsiveListItemRenderer": [
            "flexColumns": [["musicResponsiveListItemFlexColumnRenderer": ["text": ["simpleText": "91's"]]],
                            ["musicResponsiveListItemFlexColumnRenderer": ["text": ["simpleText": "PNL • 3:54"]]]],
            "overlay": ["musicItemThumbnailOverlayRenderer": ["content": ["musicPlayButtonRenderer": [
                "playNavigationEndpoint": ["watchEndpoint": ["videoId": candidate.id,
                    "watchEndpointMusicSupportedConfigs": ["watchEndpointMusicConfig": ["musicVideoType": "MUSIC_VIDEO_TYPE_ATV"]]]]]]]]]]
        check(PWDownloadRules.candidates(music, music: true).first?.youtubeEvidence == "distributed_audio_pending", "distributed Music audio metadata parsed")
        check(PWFallbackPolicy.order(soundCloud: true, audius: true) == ["soundcloud", "audius"], "fallback order")
        check(PWFallbackPolicy.order(soundCloud: false, audius: true) == ["audius"], "SoundCloud disable respected")
        check(PWFallbackPolicy.order(soundCloud: false, audius: false).isEmpty, "no forced fallback")
        // Reproduce the log's terminal YouTube failure, using the production
        // error and recovery path, rather than a successful SoundCloud fixture.
        var calls: [String] = []
        let configurationError = PWDownloadError.youtubeConfigurationUnavailable
        let recovered = try await PWFallbackPolicy.recoverYouTube(configurationError) {
            calls.append("soundcloud")
            return "complete recording"
        }
        check(recovered == "complete recording" && calls == ["soundcloud"], "unreadable YouTube configuration reaches SoundCloud despite terminal pause flag")
        let noMatchResult = try await PWFallbackPolicy.recoverYouTube(PWDownloadError(message: "no match", fallbackEligible: true)) { "soundcloud" }
        check(noMatchResult == "soundcloud", "ordinary missing matches retain fallback")
        calls.removeAll()
        let mediaResult = try await PWFallbackPolicy.recoverYouTube(NSError(domain: "media", code: 403), refusedMedia: true) {
            calls.append("soundcloud"); return "audio"
        }
        check(mediaResult == "audio" && calls == ["soundcloud"], "refused audio still reaches fallback after common media retry")
        let terminalErrors: [Error] = [PWDownloadError(message: "quota", pausesQueue: true),
                                      NSError(domain: "consent", code: 302), URLError(.cancelled),
                                      URLError(.timedOut), NSError(domain: "search HTTP", code: 429),
                                      NSError(domain: "search HTTP", code: 403)]
        for failure in terminalErrors {
            calls.removeAll()
            do {
                _ = try await PWFallbackPolicy.recoverYouTube(failure) { calls.append("soundcloud"); return "unexpected" }
                fatalError("FAIL: non-eligible provider failure was swallowed")
            } catch {
                check(calls.isEmpty, "consent, quota and transport failures do not invoke SoundCloud")
            }
        }
        calls.removeAll()
        do {
            let _: String = try await PWFallbackPolicy.recoverYouTube(configurationError) {
                for provider in PWFallbackPolicy.order(soundCloud: false, audius: false) { calls.append(provider) }
                throw configurationError
            }
            fatalError("FAIL: disabled fallback succeeded")
        } catch let error as PWDownloadError {
            check(calls.isEmpty && error.pausesQueue, "disabled fallback preserves explicit queue pause")
        }
        calls.removeAll()
        do {
            let _: String = try await PWFallbackPolicy.recoverYouTube(configurationError) {
                calls.append("soundcloud")
                throw PWDownloadError(message: "SoundCloud quota", pausesQueue: true)
            }
            fatalError("FAIL: fallback error was swallowed")
        } catch let error as PWDownloadError {
            check(calls == ["soundcloud"] && error.message == "SoundCloud quota" && error.pausesQueue, "SoundCloud failure remains visible with pause state")
        }
        let cancelled = await Task { @MainActor in
            withUnsafeCurrentTask { $0?.cancel() }
            var invoked = false
            do {
                _ = try await PWFallbackPolicy.recoverYouTube(configurationError) { invoked = true; return "unexpected" }
                return false
            } catch is CancellationError { return !invoked }
            catch { return false }
        }.value
        check(cancelled, "cancelled queue cannot start SoundCloud even for eligible configuration failure")
        check(PWRecordingPolicy.unavailableYouTubeContainer(NSError(domain: "PWAudioContainer", code: 2)), "short YouTube recording triggers fallback")
        check(!PWRecordingPolicy.unavailableYouTubeContainer(NSError(domain: "PWAudioContainer", code: 1)), "container malfunction is not hidden by fallback")
        check(!PWRecordingPolicy.unavailableYouTubeContainer(NSError(domain: NSCocoaErrorDomain, code: NSFileWriteOutOfSpaceError)), "full disk is not treated as unavailable recording")
        check(PWSoundCloudHTTPError(stage: "search", status: 403).localizedDescription.contains("search"), "metadata rejection identifies its stage")
        let client = String(repeating: "a", count: 32)
        check(PWSoundCloudRules.clientID("var x={client_id:\"\(client)\"}") == client, "public script client configuration")
        check(PWSoundCloudRules.clientID("client_id:\"short\"") == nil, "malformed configuration rejected")
        let scripts = PWSoundCloudRules.scripts("<script src=\"https://evil.test/a.js\"></script><script src='//a-v2.sndcdn.com/assets/app.js'></script>")
        check(scripts.count == 1, "only public app asset host")
        let endpoint = PWSoundCloudRules.endpoint(URL(string: "https://api-v2.soundcloud.com/search/tracks?q=91%27s&client_id=old")!, clientID: client)!
        let params = URLComponents(url: endpoint, resolvingAgainstBaseURL: false)!.queryItems!
        check(params.filter { $0.name == "client_id" }.count == 1 && params.first { $0.name == "q" }?.value == "91's", "apostrophe preserved, stale client replaced")
        for text in ["https://api-v2.soundcloud.com.evil.test/a", "http://api-v2.soundcloud.com/a", "https://user:pass@api-v2.soundcloud.com/a", "https://api-v2.soundcloud.com:8080/a"] {
            check(PWSoundCloudRules.endpoint(URL(string: text)!, clientID: client) == nil, "foreign endpoint refused")
        }
        let transcode: [String: Any] = ["url": "https://api-v2.soundcloud.com/media/123/hls", "quality": "sq", "snipped": false,
            "format": ["protocol": "hls", "mime_type": "audio/mpeg"]]
        var row: [String: Any] = ["id": 123, "title": "91’s", "duration": 234000, "policy": "ALLOW", "sharing": "public", "streamable": true,
            "user": ["username": "PNL", "verified": true], "publisher_metadata": ["artist": "PNL", "isrc": track.isrc!],
            "media": ["transcodings": [transcode]]]
        check(PWSoundCloudRules.match(row, track: track).0?.evidence == "isrc", "same full recording accepted")
        let fixture = try Data(contentsOf: URL(fileURLWithPath: "tests/fixtures/soundcloud-au-dd-public.json"))
        var publicRow = try JSONSerialization.jsonObject(with: fixture) as! [String: Any]
        let publicTrack = PWAudioTrack(id: "0123456789ABCDEFGHIJKL", title: "Au DD", artist: "PNL", duration: 247)
        check(PWSoundCloudRules.match(publicRow, track: publicTrack).0?.evidence == "verified_artist", "observed MONETIZE public PNL recording accepted without ISRC from native Spotify model")
        for policy in ["SNIP", "BLOCK", "SUB_HIGH_TIER", "unknown"] {
            var blocked = publicRow; blocked["policy"] = policy
            check(PWSoundCloudRules.match(blocked, track: publicTrack).1 == "access_policy", "public metadata cannot bypass restricted policy: " + policy)
        }
        var publicStream = (publicRow["media"] as! [String: Any])["transcodings"] as! [[String: Any]]
        publicStream[0]["snipped"] = true; publicRow["media"] = ["transcodings": publicStream]
        check(PWSoundCloudRules.match(publicRow, track: publicTrack).1 == "no_public_mp3", "MONETIZE preview still rejected")
        publicStream[0]["snipped"] = false; publicStream[0]["quality"] = "hq"; publicRow["media"] = ["transcodings": publicStream]
        check(PWSoundCloudRules.match(publicRow, track: publicTrack).1 == "no_public_mp3", "MONETIZE high-quality-only stream still rejected")
        check(PWSoundCloudRules.noMatchMessage(candidates: 0, rejections: [:]).contains("aucun titre"), "empty search distinguished from rejected candidates")
        let rejectionMessage = PWSoundCloudRules.noMatchMessage(candidates: 2, rejections: ["access_policy": 1, "provenance_unconfirmed": 1])
        check(rejectionMessage.contains("parmi 2") && rejectionMessage.contains("provenance non confirmée : 1") && rejectionMessage.contains("limité à un extrait : 1"), "error explains actual candidate rejections")
        var rejected = row; rejected["policy"] = "SNIP"
        check(PWSoundCloudRules.match(rejected, track: track).0 == nil, "paid preview rejected")
        rejected = row; rejected["sharing"] = "private"
        check(PWSoundCloudRules.match(rejected, track: track).0 == nil, "private track rejected")
        rejected = row; rejected["publisher_metadata"] = ["artist": "PNL", "isrc": "FRABC1900002"]
        check(PWSoundCloudRules.match(rejected, track: track).1 == "isrc", "different recording ISRC rejected")
        rejected = row; rejected["publisher_metadata"] = ["artist": "PNL"]; rejected["user"] = ["username": "PNL Fan", "verified": true]
        check(PWSoundCloudRules.match(rejected, track: track).1 == "provenance_unconfirmed", "fan uploader cannot borrow publisher name")
        for proto in ["encrypted-hls", "ctr-hls", "cbc-hls"] {
            var stream = transcode; stream["format"] = ["protocol": proto, "mime_type": "audio/mpeg"]
            rejected = row; rejected["media"] = ["transcodings": [stream]]
            check(PWSoundCloudRules.match(rejected, track: track).0 == nil, "encrypted protocol rejected")
        }
        var stream = transcode; stream["snipped"] = true
        row["media"] = ["transcodings": [stream]]
        check(PWSoundCloudRules.match(row, track: track).0 == nil, "snipped media rejected despite full track metadata")
        let base = URL(string: "https://cf-hls-media.sndcdn.com/playlist/audio.m3u8")!
        let hls = "#EXTM3U\n#EXT-X-TARGETDURATION:6\n#EXTINF:6,\n../segment1.mp3\n#EXTINF:6,\nhttps://cf-media.sndcdn.com/segment2.mp3\n#EXT-X-ENDLIST\n"
        check(PWSoundCloudRules.segments(hls, base: base, expectedDuration: 12)?.count == 2, "finite MP3 HLS accepted")
        check(PWSoundCloudRules.segments(hls, base: base, expectedDuration: 60) == nil, "preview manifest duration rejected")
        check(PWSoundCloudRules.segments(hls.replacingOccurrences(of: "#EXT-X-ENDLIST", with: ""), base: base, expectedDuration: 12) == nil, "live/incomplete HLS rejected")
        for tag in ["#EXT-X-KEY:METHOD=AES-128,URI=\"key\"", "#EXT-X-MAP:URI=\"init\"", "#EXT-X-BYTERANGE:100@0", "#EXT-X-GAP", "#EXT-X-STREAM-INF:BANDWIDTH=128000"] {
            check(PWSoundCloudRules.segments(hls.replacingOccurrences(of: "#EXTM3U", with: "#EXTM3U\n" + tag), base: base, expectedDuration: 12) == nil, "unsupported/encrypted HLS rejected")
        }
        check(PWSoundCloudRules.segments(hls.replacingOccurrences(of: "https://cf-media.sndcdn.com/segment2.mp3", with: "https://evil.test/a.mp3"), base: base, expectedDuration: 12) == nil, "HLS cannot redirect to arbitrary site")
        check(!PWSoundCloudRules.mediaURL(URL(string: "https://cf-media.sndcdn.com/preview/audio.mp3")!), "preview URL refused")
        check(!PWSoundCloudRules.mediaURL(URL(string: "https://sndcdn.com.evil.test/audio.mp3")!), "CDN suffix attack refused")
        check(PWDownloadLog.clean("client_id=private track_authorization=secret").contains("private") == false, "web configuration excluded from diagnostics")
        print("PASS: \(count) official recording and SoundCloud checks")
    }
}
